# syntax=docker/dockerfile:1.7
FROM node:24.20.0-alpine as installer
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable && corepack install --global pnpm@10.34.0
WORKDIR /app
COPY package.json pnpm-lock.yaml .npmrc ./
RUN --mount=type=secret,id=npm_token,required=true \
    NPM_TOKEN="$(cat /run/secrets/npm_token)" \
    pnpm install --frozen-lockfile && \
    rm .npmrc
FROM installer as builder
WORKDIR /app
COPY .swcrc ./
COPY ./src  ./src
RUN pnpm run build
RUN pnpm prune --prod

FROM node:24.20.0-alpine as prod-server
WORKDIR /app
COPY --from=builder app/package.json .
COPY --from=builder app/pnpm-lock.yaml .
COPY --from=builder app/dist ./dist
COPY --from=builder app/node_modules ./node_modules

CMD ["dist/index-worker.js"]
